#!/usr/bin/env bash

repos=(
  'github.com/rubenv/sql-migrate/...'
  'github.com/lib/pq'
  'github.com/jmoiron/sqlx'
  'github.com/gocraft/web'
  'github.com/opennota/json-binding'
  'github.com/extemporalgenome/slug'
  'github.com/dgrijalva/jwt-go'
  'golang.org/x/crypto/bcrypt'
  'gopkg.in/check.v1'
  'gopkg.in/yaml.v2'
);

for repo in "${repos[@]}"; do
  echo 'go get -u' $repo
  `go get -u $repo`
done
